name: openmm-cookbook
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - openmm
  - pydata-sphinx-theme
  - pip:
    - m2r2
    - GitPython
    - sphinx
    - sphinx-autoapi
    - setuptools


